version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6541:5432"
    volumes:
      - stats_data:/var/lib/postgresql/data

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "6542:5432"
    volumes:
      - ewm_data:/var/lib/postgresql/data

volumes:
  stats_data:
  ewm_data: