spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          time_zone: UTC
          default_schema: public

  datasource:
    #url: jdbc:postgresql://localhost:5432/stats
    url: jdbc:postgresql://localhost:6432/stats
    username: stats
    password: stats
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

client:
  url: http://localhost:9090